export const affixGroups = [
  { title: "MOST COMMON PREFIXES", rows: [
    ["ANTI-", "against", "anti-Semitic, antisocial"], ["BI-", "double or twice", "biannual, bipartisan"], ["CO-", "together with", "cooperate, coexist"], ["COUNTER-", "in opposite direction", "counterpoint, counterattack"], ["DE-", "undo action of verb it is attached to", "decentralize, depopulate"], ["EN-", "makes verbs, to make or to put into the state of", "enlarge, enrich, endanger"], ["EX-", "former", "ex-minister, ex-wife"], ["INTER-", "between", "international, interracial"], ["OUT-", "do better or more than", "outgrow, outlive, outdo"], ["OVER-", "too much", "overwork, overcook"], ["POST-", "after", "postdate, postgraduate"], ["PRE-", "before", "prenatal, pre-war"], ["RE-", "again", "repaint, rebuild"], ["SELF-", "alone, independent", "self-study, self-service"], ["SEMI-", "half", "semi-final, semidetached"], ["SUB-", "under, inferior to", "subordinate, subnormal"], ["UNDER-", "not enough", "underpay, undercook"]
  ]},
  { title: "NEGATIVE PREFIXES", rows: [
    ["DIS-", "exact opposite", "disadvantage, disconnect, dislike"], ["IL-", "used before ‘l’", "illegal, illiterate, illogical"], ["IM-", "used before ‘b’, ‘m’ and ‘p’", "impossible, immoral, imbalanced"], ["IN-", "often used with words of Latin origin", "incredible, invisible, inaccessible, indifferent"], ["IR-", "used before ‘r’", "irrelevant, irresponsible"], ["MIS-", "means that the action has been incorrectly or inadequately performed", "misunderstand, misinform, misuse"], ["NON-", "also used with verbs to express that the action described by the verb is not performed", "non-smoker, nonconformist, non-stop, non-negotiable"], ["UN-", "frequently found with words of English origin", "unbelievable, unpleasant, unbearable, unreasonable"]
  ]},
  { title: "SUFFIXES TO MAKE ADJECTIVES", rows: [
    ["N + -AL", "added to nouns", "formal, original, additional"], ["N + -FUL", "filled with or having", "peaceful*, faithful, successful*, forgetful*"], ["N + -LESS", "opposite of adjectives with ‘-ful’. *not all take both ‘ful’ and ‘less’", "careless, harmless, faithless, noiseless*"], ["N + -LIKE", "resembling or in the manner of", "warlike, ladylike, godlike"], ["N + -LY", "having the quality or appearance of (person); occurs or appears every", "beastly, fatherly, ghostly; weekly, daily, yearly"], ["N + -Y", "having the quality of or appearance of (uncountable noun)", "healthy, guilty, salty, sandy"], ["N + -OUS / -IOUS / -EOUS", "like, full of or relating to", "dangerous, glorious, spontaneous"], ["N/Vb + -SOME", "added to verbs or nouns with a causative sense", "loathsome, quarrelsome, tiresome"], ["N + -WORTHY", "worthy of or suitable for", "blameworthy, noteworthy, trustworthy"], ["N/Adj + -ISH", "having the bad qualities of (animal/person); nationality; rather/slightly (colours and other adjectives)", "childish, mulish; Swedish, Polish; reddish, greenish, coldish"], ["N/Vb + -ABLE/-IBLE", "able to be", "eatable, responsible, regrettable, fashionable"], ["Vb + -IVE", "added to verbs", "active, constructive, conclusive"]
  ]},
  { title: "SUFFIXES TO MAKE VERBS", rows: [
    ["N/Adj + -EN", "to make", "blacken, soften, harden, strengthen"], ["N/Adj + -(I)FY", "to make", "terrify, falsify, purify, intensify"], ["N/Adj + -IZE", "to make", "computerize, fertilize, tranquilize"], ["N + -ATE", "to make; inseparable", "isolate, congratulate, speculate"]
  ]},
  { title: "SUFFIXES TO MAKE NOUNS", rows: [
    ["Vb + -AGE", "added to verbs, forms name of the action", "marriage, breakage"], ["Vb + -AL", "added to verbs, forms name of the action", "survival, recital, removal"], ["Vb + -ANCE/-ENCE", "the action of … / the results of the action of…", "assistance, interference"], ["Vb + -ANT", "added to verbs", "assistant, emigrant, accountant"], ["Vb + -ATION/-ITION", "the action of … / the results of the action of…", "declaration, composition"], ["Vb + -EE", "a person to whom something is done", "employee, absentee, refugee"], ["Vb + -ER/-OR/ -AR", "the person who does / who is connected with", "teacher, visitor, beggar"], ["Vb + -MENT", "the action of … / the results of the action of…", "development, government"], ["Vb + -ION/-SION/-TION", "can be found in these different spellings", "relation, confession, information"], ["N/Vb + -ESS", "makes feminine forms", "heiress, waitress"], ["N/Vb + -EER", "a person associated with something", "auctioneer, mountaineer"], ["N/Adj + -DOM", "the state of being (a)", "kingdom, freedom"], ["N + -FUL", "with things which can contain or hold something", "handful, mouthful, spoonful"], ["N + -HOOD", "the state of being a", "neighbourhood, fatherhood, motherhood"], ["N + -IST/-AN/-IAN", "the person associated with certain things and places", "typist, dramatist, Roman, magician, electrician"], ["N + -SHIP", "words ending in –er and –or usually have the suffix; words ending in –man also have the suffix (the art/skill of a …)", "friendship, membership, dictatorship; workmanship, craftsmanship"], ["Adj + -NESS", "makes abstract nouns", "illness, sadness, weakness, kindness"], ["Adj + -TY/-ITY", "can be found in these different spellings", "cruelty, loyalty, similarity, formality"]
  ]}
];