import React from "react";
import { ExternalLink, Globe2 } from "lucide-react";
import AppShell from "@/components/AppShell";

const channels = [
  ["BBC News", "Reino Unido", "Cobertura informativa global, análisis profundos y reportajes de investigación con el estilo característico del servicio público británico.", "https://www.youtube.com/@BBCNews"],
  ["BBC World Service", "Reino Unido", "Enfoque internacional con documentales originales y perspectivas detalladas sobre temas globales y regionales fuera de Occidente.", "https://www.youtube.com/@BBCWorldService"],
  ["Sky News", "Reino Unido", "Canal de noticias de última hora con cobertura dinámica y programas especiales de debate sobre política británica e internacional.", "https://www.youtube.com/@SkyNews"],
  ["NBC News", "Estados Unidos", "Información basada en hechos, transmisiones en directo y reportajes de actualidad con fuerte énfasis en el contexto estadounidense y global.", "https://www.youtube.com/@NBCNews"],
  ["Al Jazeera English", "Catar", "Perspectiva internacional alternativa con un enfoque profundo en historias del Sur Global y debates sobre temas geopolíticos complejos.", "https://www.youtube.com/@aljazeeraenglish"],
  ["France 24 English", "Francia", "Noticias internacionales desde una mirada europea y francesa, ofreciendo reportajes culturales y análisis de la política exterior europea.", "https://www.youtube.com/@France24_en"],
  ["Euronews English", "Unión Europea (Francia)", "Perspectiva paneuropea sobre los acontecimientos políticos, económicos y sociales que impactan a la Unión Europea y al mundo.", "https://www.youtube.com/@euronews"],
  ["DW News", "Alemania", "Periodismo riguroso desde Alemania, centrado en asuntos europeos, innovación, ciencia y un análisis internacional independiente.", "https://www.youtube.com/@dwnews"],
  ["WION", "India", "Canal internacional de noticias desde India, con cobertura global y análisis sobre política, economía, tecnología y acontecimientos del Sur Global.", "https://www.youtube.com/@WION"]
];

export default function News() {
  return <AppShell><main className="mx-auto max-w-6xl px-5 py-10"><section className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-600">Watch · News</p><h1 className="mt-3 font-heading text-3xl font-bold tracking-tight sm:text-4xl">Actualidad internacional</h1><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-slate-300">Aprender un idioma no es solo dominar su gramática y vocabulario, sino también entender las diferentes realidades culturales, sociales y políticas que moldean el mundo actual. Escuchar noticias en inglés desde diversas fuentes te otorga una ventaja analítica inigualable.</p><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">Cada medio transmite desde una perspectiva geográfica, política y cultural única. Al contrastar varias versiones de un mismo acontecimiento, perfeccionarás tu comprensión auditiva y fluidez, desarrollarás pensamiento crítico y podrás construir tus propias conclusiones informadas.</p></section><section className="mt-12"><h2 className="flex items-center gap-2 font-heading text-2xl font-bold"><Globe2 className="text-indigo-600" size={24}/> Canales de noticias en YouTube</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{channels.map(([name, country, description, url]) => <a key={name} href={url} target="_blank" rel="noreferrer" className="rounded-2xl border border-indigo-100 bg-white/70 p-6 shadow-sm transition hover:-translate-y-1 hover:border-indigo-300 hover:shadow-lg dark:border-white/10 dark:bg-white/5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-heading text-lg font-bold">{name}</h3><p className="mt-1 text-sm font-medium text-indigo-600">{country}</p></div><ExternalLink size={18} className="shrink-0 text-indigo-600"/></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></a>)}</div></section></main></AppShell>;
}