import React from "react";

const Line = ({ children, className = "" }) => <p className={`mb-5 min-h-[20px] text-[15px] leading-5 ${className}`}>{children}</p>;
const Heading = ({ children }) => <h2 className="mb-7 mt-16 text-[15px] font-bold leading-5">{children}</h2>;

export default function InversionConditionalsDocument({ onSelect }) {
  const selectText = () => { const text = window.getSelection().toString().trim(); if (text) onSelect(text); };
  return <article onMouseUp={selectText} className="mx-auto max-w-[794px] select-text bg-white px-12 py-24 text-black shadow-sm sm:px-24"><h1 className="mb-20 text-center text-[15px] font-bold underline">Inversions with the Conditionals</h1>
    <Heading>Zero Conditional</Heading><Line>If + present simple + present simple</Line><Line>If you require any further information, please do not hesitate to contact me.</Line><Line>If you <strong>should</strong> require any further information, please do not hesitate to contact me.</Line><Line><strong>Should</strong> you require any further information, please do not hesitate to contact me.</Line><Line>If you have any doubt, please, go to the book.</Line><Line>If you <strong>should</strong> have any doubt, please, go to the book.</Line><Line><strong>Should</strong> you have any doubt, please, go to the book.</Line>
    <Heading>First Conditional</Heading><Line>If + present simple + will</Line><Line>If you study for the exam, you will pass it.</Line><Line>If you <strong>should</strong> study for an exam, you will pass it.</Line><Line><strong>Should</strong> you study for the exam, you will pass it.</Line><Line>If you work the whole month, you will have more money to travel.</Line><Line>If you <strong>should</strong> work the whole month, you will have more money to travel.</Line><Line><strong>Should</strong> you work the whole month, you will have more money to travel.</Line><Line>If I work hard, I will have a good future.</Line><Line>If I should work hard, I will have a good future.</Line><Line><strong>Should</strong> I work hard, I will have a good future.</Line>
    <Heading>Second Conditional</Heading><Line>If + past simple + would + inf</Line><Line>If I worked more at my job, I would not have to work at home.</Line><Line><u>If I were to work</u> more at my job, I would not have to work at home. (no inversion here/this structure exists too)</Line><Line className="mt-16"><strong>Were I</strong> to work more at my job, I would not have to work at home.</Line><Line>If I didn’t have a car, it would take me a lot longer to get to my university.</Line><Line>If I weren’t to have a car, it would take me a lot longer to get to my university.</Line><Line><strong>Were I not</strong> to have a car, it would take me a lot longer to get to my university.</Line><Line className="mt-16">If you won the lottery, what would you do?</Line><Line>If you were to win the lottery, what would you do?</Line><Line><strong>Were you</strong> to win the lottery, what would you do?</Line><Line>If you worked abroad, would you enjoy the experience?</Line><Line>If you were to work abroad, would you enjoy the experience?</Line><Line><strong>Were you</strong> to work abroad, would you enjoy the experience?</Line>
    <Heading>Third Conditional</Heading><Line><strong>If + past perfect + would have + participle</strong></Line><Line>If I hadn’t left university, I would not have entered a film school.</Line><Line><strong>Had I not</strong> left university, I would not have entered a film school.</Line><Line>If I had gone to bed earlier last night, I would have gotten up earlier.</Line><Line><strong>Had I gone</strong> to bed earlier last night, I would have gotten up earlier.</Line><Line>If I hadn’t become a teacher, I would have been working in a factory.</Line><Line><strong>Had I not</strong> become a teacher, I would have been working in a factory.</Line><Line>If I hadn’t stopped playing basketball, I would have continued with my basketball career.</Line><Line><strong>Had I not</strong> stopped playing basketball, I would have continued with my basketball career.</Line>
    <Line className="mt-16"><strong>Were it not for + would have: Used in a similar way to the third conditional.</strong></Line><Line>Were it not for good friends, I wouldn’t have taken the risk to take this job.</Line><Line>Were it not for my friends, I would have had a boring childhood.</Line><Line>Were it not for the good times, life would be boring.</Line><Line className="mt-16"><strong>Were I to</strong> is not the same as <strong>Were it for</strong></Line><Line>Were I to = 2nd conditional</Line><Line>Were it for/ Were it not for: 2nd and 3rd</Line>
    <h1 className="mb-16 mt-20 text-center text-[15px] font-bold">Inversions with the Conditionals Conversation</h1><Heading>Zero Conditional</Heading><Line>Where can you find the following written: <u><strong>Should</strong> you require any further information, please, do not hesitate to contact me?</u></Line><Line>Where can you hear the following: <strong>Should</strong> you have any doubt, please, go to page 25?</Line><Heading>First Conditional</Heading><Line><u><strong>Should</strong> you not</u> study hard for an exam, will you be able to pass it?</Line><Line><strong>Should</strong> you work extra time, how much extra money will you have to spend on travelling?</Line><Line><strong>Should</strong> I not work hard, will I still have a good future?</Line><Heading>Second Conditional</Heading><Line><strong>Were I</strong> to drive to the capital of your country right now, how long would it take me to get there?</Line><Line><strong>Were you</strong> to win the lottery, what would you do?</Line><Line><strong>Were you</strong> to work abroad, would you enjoy the experience?</Line><Heading>Third Conditional</Heading><Line><strong>Had you not</strong> left university when you did, what would you have accomplished before leaving by studying more?</Line><Line><strong>Had you gone</strong> to bed later last night, would you still have gotten up at the same time this morning?</Line><Line><strong>Had you</strong> chosen another profession/degree/extracurricular activity/job, what would it have been?</Line><Line className="mt-16">Were it not for + would have: Used in a similar way to the third conditional.</Line><Line><strong>Were it not for</strong> the support of my friends/teachers, what kind of a time would I have had at school?</Line><Line><strong>Were it not for</strong> playing sports, would I still have had a healthy childhood?</Line><Line><strong>Were it not for</strong> the good times, would Mark and Maria (my friends) have been able to avoid a divorce after a turbulent period?</Line><Line className="mt-16">Were I to is not the same as Were it for</Line><Line>Were I to = 2nd conditional only</Line><Line>Were it for/ Were it not for: used in 2nd and 3<sup>rd</sup> conditionals</Line>
  </article>;
}