import React from "react";

export default function ParticipleClauseDocument({ onSelect }) {
  const selectText = () => {
    const text = window.getSelection().toString().trim();
    if (text) onSelect(text);
  };

  return <article onMouseUp={selectText} className="mx-auto min-h-[1123px] max-w-[794px] select-text bg-white px-8 py-20 text-black shadow-sm sm:px-16"><div className="space-y-6 text-[15px] leading-7"><p>Are Participle clauses a type of subordinate clause that use a present or past participle verb form?</p><p>Are they used to add extra information to a sentence?</p><p>Can they be used to describe an action that happened before or after the main clause?</p><p>Do they talk about the same subject in both clauses?</p><div className="h-10"/><p>The most common types of participle clauses are:</p><p>1: Present Participle Clauses: Do these clauses use the present participle form of the verb (ending in -ing)? Are they used to describe an action that is happening at the same time as the main clause?</p><p>Example: Running down the street, he saw his old friend.</p><p className="font-bold">Running down the street, have you ever tripped up and fallen down?</p><p className="font-bold">Watching a sad movie, have you ever started to cry?</p><p className="font-bold">Doing you work, have you ever fallen asleep?</p><div className="h-10"/><p>2: Past Participle Clauses: Do these clauses use the past participle form of the verb (ending in -ed)? Are they used to describe an action that happened before the main clause?</p><p>Examples:</p><p>a: Having been exhausted from his long journey, he finally arrived home.</p><p>b: reduced form : (Having been) Exhausted from his long journey, he finally arrived home.</p><p>Do we use this only for passive voice structures?</p><p className="font-bold">Exhausted from your journey, when was the last time you arrived home and just collapsed on your bed?</p><p className="font-bold">Disappointed after a failed job interview, what do you think my friend, John did next?</p><p className="font-bold">Explained her tasks unclearly, how well do you think my friend, Maria did those tasks?</p><div className="h-10"/><p>3: Perfect Participle Clauses: Do these clauses use both the present and past participles forms of the verb (ending in -ing and -ed)? Are they used to describe an action that happened before and is still relevant to the main clause? Can we use this structure for the passive voice and the active voice, both?</p><div className="h-10"/><p>Example: Having worked hard all day, he was ready for a rest.</p><p className="font-bold">Having done something heroic, when was the last time you saw someone receive an award?</p><p className="font-bold">Having finished your meal, when was the last time you went for a walk with your family to digest your food?</p><p className="font-bold">Having moved to a new city, what do you think my friend John’s parents did to settle down?</p></div></article>;
}