import React from "react";

const sections = [
  ["With", ["Why must you be acquainted with all the facts before stating your opinion?", "Whose interpretation of situations do you never agree with in your family and friends?", "What are you busy with these days?", "What should happen to an underage suspect who has been arrested and charged with robbery?", "When was the last time you were delighted with something you had bought?", "Are you familiar with Japanese culture?", "What would make you furious with someone?", "What was the last performance you were really impressed with?", "What are you pleased with achieving in your life?", "How can you be very popular with/among your classmates/workmates?", "Who is the last person you had a quarrel/an argument with?", "How can you have a good relationship with your siblings forever?", "Why should injured people be taken to hospital without delay?"]],
  ["To", ["What kind of person would you never agree to marry?", "How much money is your car worth to you this year?", "How can governments successfully appeal to the public to stay calm during a crisis?", "How attached are/were you to your parents?", "If someone looked familiar to you, how would you approach them to clarify?", "Do you know anyone who is identical to another member of their family?", "Do you know anyone who got married to a businessman/businesswoman?", "What is it like when you are new in/to an area?", "What kinds of changes are obvious to you that our society needs?", "Who is a person in your life that is always pleasant to everyone?", "Why should parents be sensitive to the needs of their children?", "Have you ever seen a goalkeeper throw the ball to his team-mate only for the ball to be taken by a player from the opposing team?", "Talk about someone who was able to accomplish something to your astonishment."]],
  ["Of", ["How can you teach kids to be more aware of their own actions?", "Do/Did your parents approve of your hairstyle?", "What kind of behaviour at parties should drunken people be ashamed of?", "What are some good ways of taking care of your health?", "When was the last time it was really nice of someone to treat you to a meal?", "What did your grandparents die of?", "What do you dream of accomplishing/achieving in your life?", "Who are you really fond of in your family?", "Which products do you think everyone in the world has heard of?", "Why is it a bad idea to be jealous of others?", "What would you do if there is a lack of money in your family?", "What is there no more need of in your world?", "How would you try to help kids who take no notice of warnings and do risky things?", "What kinds of things make parents proud of their kids?", "Do you like bread that tastes of garlic?", "What kinds of mistakes are typical of you when speaking English?", "Would you let a friend make use of your car while you were away on holiday?"]],
  ["On", ["Why are there so many attacks on foreign military bases in Africa/some parts of Asia?", "Do you like films which are based on a true story?", "Please, advise us on how to discourage burglars.", "Do you know any siblings who always put the blame on each other for things that they haven’t done?", "When was the last time you congratulated someone on passing their exams?", "What would you put emphasis on when talking about improving your English?", "How can you make a good impression on your employer/colleagues?", "What are you keen on?", "Why is it considered rude to listen to someone in authority while leaning on/leaning against something like a wall or a window?", "Have you ever been operated on?", "How much milk do you buy on average, every week?", "Do you inform your family and friends if you are on the way to see them?", "Talk about an experience that had a few hiccups but you enjoyed it on the whole?", "Would you forgive someone who hurt you really badly but it wasn’t on purpose?", "What do most kids spend their pocket money on?", "Why do workers go on strike?", "What responsibilities do nurses have when they are on duty?", "What would you do if you saw a house on fire?", "How does a family cope when one of the parents is away on business for a long time?", "What would you do if you left your wallet/purse on the bus when you got off?", "How do you pass your time when you are on a plane?"]],
  ["At", ["What are you really bad at doing?", "If you aimed at the target and fired your gun, what are the chances of you hitting the target?", "What sports are you good at?", "Do you know someone who is a genius at Maths?", "When was the last time you had to pass an exam at all costs?", "How do you feel at the end of a really sad programme?", "When was the last time you saw someone so angry that they could have thrown something at another person?", "Would you manage to sell your house at a profit if you put it up for sale?"]],
  ["For", ["When was the last time you blamed someone for doing something wrong?", "Do you agree with there being an extra charge for delivering the goods to your home?", "Why is it very important nowadays to care about/for our environment?", "How fond are you of your parents and how much do you care for them?", "What is London famous for?", "What kind of weather are you hoping for, for this weekend?", "What kind of reckless action is there never a reason for in a relationship?", "How long is a driving license valid for?", "How would you show that you were sorry for hurting someone’s feelings?", "Where would you like to take a holiday for a change?"]],
  ["About", ["Do you know someone who is always complaining about having too much work?", "What did you dream about last night?", "What kinds of things do couples have a quarrel about?", "Why do people warn their children about talking to strangers?", "Are you sorry about anything you have done which hurt someone you know?"]],
  ["In", ["Do you know anyone who died in an accident?", "Why is it useful to be experienced in first aid?", "Does your failure in an exam mean that you are not intelligent?", "Do you know anyone who specialises in a certain medical field?", "Are your qualifications valid in other countries?", "Do you enjoy walking in the hills?", "Why are so many species in danger of extinction?", "What are some common reasons why children get so upset that they are in tears at school?", "Talk about a concept that you had to study for a really long time, but, fortunately, in the end, you understood it.", "When was the last time you broke a chocolate into pieces to share with your friends?"]],
  ["From", ["Which holiday of yours has been really different from all the others?", "Talk about an old friend you haven't heard from for a long time.", "What kinds of things would prevent a plane from taking off?", "How long would it take you to recover from a broken leg?", "Have you ever seen someone save another person from an accident?", "How many names of the world’s capital cities can you say from memory?"]],
  ["Between", ["What difference is there between English and Spanish food?", "Why do people still smoke when they know clearly that there is a strong relationship between smoking cigarettes and lung cancer?"]],
  ["Under", ["What kinds of new laws are under discussion?", "Are there any roads under repair in your area?", "Do you think that everything is under control with regards to society these days?"]],
  ["By", ["Do you usually go to other cities by bus or train?", "Have you ever put salt instead of sugar in your tea/coffee by mistake?", "Talk about someone who you know only by sight but you want to speak to them.", "Do you know someone who can make really nice things by hand?", "Who would you inform if you saw a small child outside all by himself/herself?", "As an actor/actress, would you be able to learn your part by heart easily?"]],
  ["Out of", ["How easily do you get out of breath?", "Talk about a place where the lift is/some facilities are out of order all the time.", "Would you stay on the platform until the train was out of sight if you go to see someone off?"]],
  ["Off", ["What kinds of excuses are beside/off the point and are not relevant at all when we are talking about giving up a bad habit?", "What is the first thing you would do when you go off duty after a really hard day at work?"]],
  ["Against", ["Why is it against the law to drive a car without wearing a seatbelt?"]],
  ["To vs. At", ["When was the last time you saw someone so angry that they would have thrown something at another person?", "Have you ever seen a goalkeeper throw the ball to his team-mate only for the ball to be taken by a player from the opposing team?"]]
];

export default function VerbsPrepositionsDocument({ onSelect }) {
  const selectText = () => { const text = window.getSelection().toString().trim(); if (text) onSelect(text); };
  return <article onMouseUp={selectText} className="mx-auto min-h-[1123px] max-w-[794px] select-text bg-white px-8 py-24 text-black shadow-sm sm:px-[120px]"><h2 className="text-center font-document text-2xl">Question Answer Series to Practise English at Home</h2><p className="mb-10 mt-6 text-center font-document text-xl">Dependent Preposition Practice</p><div className="space-y-9">{sections.map(([heading, questions]) => <section key={heading}><h3 className="mb-5 font-document text-lg font-bold">{heading}</h3>{questions.map((question) => <p key={question} className="font-document text-[15px] leading-6">{question}</p>)}</section>)}</div></article>;
}