import React from "react";
import { ArrowRight, BriefcaseBusiness, GraduationCap, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const highlights = [
  [GraduationCap, "Curso 1:1 para hispanohablantes"],
  [BriefcaseBusiness, "Trabajo, estudios y vida diaria"],
  [Sparkles, "Profesor CELTA + herramientas de IA"]
];

export default function Hero() {
  return <section className="relative overflow-hidden px-5 pb-20 pt-16 sm:pb-28 sm:pt-24"><div className="absolute inset-x-0 top-0 -z-10 mx-auto h-[32rem] max-w-5xl rounded-full bg-indigo-300/30 blur-3xl dark:bg-cyan-500/10" /><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div className="text-center lg:text-left"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white/70 px-4 py-2 text-sm font-medium text-indigo-700 shadow-sm dark:border-indigo-400/20 dark:bg-white/5 dark:text-indigo-300"><Sparkles size={15}/> Inglés diseñado a tu medida</p><h1 className="text-balance font-heading text-4xl font-bold tracking-tight sm:text-6xl">Inglés 1:1 para comunicarte con seguridad, donde estés.</h1><p className="mt-6 max-w-2xl text-pretty text-lg leading-8 text-slate-600 dark:text-slate-300">Un curso personalizado para hispanohablantes de España y del mundo que quieren avanzar en el trabajo, los estudios y la vida diaria.</p><p className="mt-4 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300">Trabaja con un profesor cualificado con Cambridge CELTA y ayudas de IA integradas en cada lección.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><Link to="/comenzar" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white shadow-lg shadow-indigo-500/25 transition hover:-translate-y-0.5 hover:bg-indigo-700">Comenzar <ArrowRight size={18}/></Link><a href="#metodologia" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white/70 px-6 py-3 font-semibold transition hover:bg-white dark:border-white/15 dark:bg-white/5">Descubrir cómo funciona</a></div></div><div className="rounded-3xl border border-white/80 bg-white/70 p-5 shadow-2xl shadow-indigo-950/10 backdrop-blur dark:border-white/10 dark:bg-white/5 sm:p-7"><p className="font-heading text-lg font-bold">Tu aprendizaje, con una dirección clara</p><div className="mt-5 space-y-3">{highlights.map(([Icon, text]) => <div key={text} className="flex items-center gap-3 rounded-2xl bg-indigo-50/80 p-4 text-sm font-semibold text-slate-700 dark:bg-white/10 dark:text-slate-100"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white"><Icon size={18}/></span>{text}</div>)}</div><p className="mt-5 text-sm leading-6 text-slate-500 dark:text-slate-300">Objetivos reales, práctica útil y acompañamiento continuo desde la primera clase.</p></div></div></section>;
}